name: Pack apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.x'

      - name: Install .NET workloads
        run: |
          dotnet nuget locals all --clear
          dotnet workload install maui-android
          dotnet workload install maui-ios

      - name: Restore Android
        run: dotnet restore ${{ github.workspace }}/DatadogSDK/android/DatadogSdk.Android.Binding/DatadogSdk.Android.Binding.csproj

      - name: Grant execute permission for gradlew
        run: chmod +x ${{ github.workspace }}/DatadogSDK/android/native/gradlew
        
      - name: Build Android
        run: dotnet build ${{ github.workspace }}/DatadogSDK/android/DatadogSdk.Android.Binding/DatadogSdk.Android.Binding.csproj --configuration Release --no-restore

      - name: Pack Android
        run: dotnet pack ${{ github.workspace }}/DatadogSDK/android/DatadogSdk.Android.Binding/DatadogSdk.Android.Binding.csproj --configuration Release --output ${{ github.workspace }}/packages

      - name: Xcode select
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer
        
      - name: Restore iOS
        run: dotnet restore ${{ github.workspace }}/DatadogSDK/macios/DatadogSdk.MaciOS.Binding/DatadogSdk.MaciOS.Binding.csproj

      - name: Build iOS
        run: dotnet build ${{ github.workspace }}/DatadogSDK/macios/DatadogSdk.MaciOS.Binding/DatadogSdk.MaciOS.Binding.csproj --configuration Release --no-restore

      - name: Pack iOS
        run: dotnet pack ${{ github.workspace }}/DatadogSDK/macios/DatadogSdk.MaciOS.Binding/DatadogSdk.MaciOS.Binding.csproj --configuration Release --output ${{ github.workspace }}/packages

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packed-apps
          path: ${{ github.workspace }}/packages
